# https://hub.docker.com/_/ubuntu
FROM ubuntu:noble-20260217

RUN \
    apt-get \
        update \
    && \
    apt-get \
        install \
            --assume-yes \
            --no-install-recommends \
            ca-certificates=20240203 \
            curl=8.5.0-2ubuntu10.8 \
    && \
    curl \
        -fsSL \
            https://deb.nodesource.com/setup_24.x \
            | \
            bash - \
    && \
    apt-get \
        update \
    && \
    apt-get \
        install \
            --assume-yes \
            --no-install-recommends \
            git=1:2.43.0-1ubuntu7.3 \
            nodejs=24.12.0-1nodesource1 \
            make=4.3-4.1build2 \
            gpg=2.4.4-2ubuntu17.4 \
            xz-utils=5.6.1+really5.4.5-1ubuntu0.2 \
            python3-pip=24.0+dfsg-1ubuntu1.3 \
            python3-venv=3.12.3-0ubuntu2.1 \
    && \
    apt-get \
        clean \
    && \
    rm \
        -r \
        -f \
        /var/lib/apt/lists/* \
    && \
    # https://docs.anthropic.com/en/docs/claude-code/setup#standard-installation
    npm \
        install \
            --global \
            @anthropic-ai/claude-code \
    && \
    true;
